import type { CeoSlideDeckConfig } from "./types";
import { CEO_SLIDE_DECK_VERSION } from "./types";

/** Factory defaults aligned to reference board slides (finance team placeholders). */
export function defaultCeoSlideDeck(): CeoSlideDeckConfig {
  return {
    version: CEO_SLIDE_DECK_VERSION,
    financialPerformance: {
      title: "Financial Performance: Revenue & Composition",
      totalRevenueByYear: [
        { label: "FY24", value: 8698 },
        { label: "FY25", value: 8746 },
        { label: "FY26E", value: 10500 },
      ],
      composition: [
        { year: "FY24", existing: 5764, rampUp: 2365, anew: 574 },
        { year: "FY25", existing: 6240, rampUp: 2024, anew: 482 },
        { year: "FY26E", existing: 7790, rampUp: 2624, anew: 149 },
      ],
      metricCards: [
        { primary: "20%", title: "YoY Growth", sub: "FY25 to FY26E" },
        { primary: "25%", title: "Ramp-Up Share", sub: "Of total FY26E revenue" },
        { primary: "50K", title: "Revenue Per Hire", sub: "Consistent & stable" },
      ],
      landExpandTitle: "Land & Expand:",
      landExpandBody:
        "Ramp-up revenue 27% (FY24) and 25% (FY26E) of total revenue, while existing client revenue expanded 35% — proving strong account expansion dynamics.",
    },
    scaleEfficiency: {
      title: "Scale & Efficiency: Volume, Productivity & Economics",
      hiringVolume: [
        { year: "FY24", volume: 24749, rphSub: "RPH: 35,146" },
        { year: "FY25", volume: 17716, rphSub: "RPH: 49,370" },
        { year: "FY26E", volume: 21178, rphSub: "RPH: 49,939" },
      ],
      revenuePerEmployee: [
        { year: "FY24", value: 104760 },
        { year: "FY25", value: 118514 },
        { year: "FY26E", value: 156844 },
      ],
      kpiTable: {
        headers: ["", "FY24", "FY25", "FY26", "Δ"],
        rows: [
          { metric: "RPH", fy24: "35,000", fy25: "49,000", fy26: "49,000", delta: "+42%" },
          { metric: "Headcount", fy24: "774", fy25: "705", fy26: "655", delta: "-15%" },
          { metric: "Productivity", fy24: "1.05L", fy25: "1.19L", fy26: "1.57L", delta: "+50%" },
          { metric: "CM", fy24: "32%", fy25: "37%", fy26: "41%", delta: "+09pp" },
        ],
      },
      efficiencyTitle: "Efficiency Story",
      efficiencyBody:
        "Revenue recovering to 105 Cr while headcount reduced 15% from FY24 — driving 50% productivity improvement. Contribution margin expanded from 32% to 43% across top 10 accounts, signaling sustainable operating leverage.",
    },
    industryDiversification: {
      title: "Industry Diversification: Balanced Revenue Mix",
      subtitle: "",
      donutLabel: "FY26E mix",
      donutSegments: [
        { name: "Automotive", pct: 26, color: "#e16f3d" },
        { name: "IT/ITES", pct: 20, color: "#c45c2a" },
        { name: "Industrial / Mfg", pct: 15, color: "#f4a574" },
        { name: "Others", pct: 12, color: "#9ca3af" },
        { name: "Manufacturing", pct: 9, color: "#64748b" },
        { name: "Healthcare", pct: 8, color: "#60a5fa" },
        { name: "Metals / Steel", pct: 5, color: "#5eead4" },
        { name: "Cement", pct: 4, color: "#14b8a6" },
      ],
      tableTitle: "FY26E vs FY24",
      tableSubtitle: "Industry Revenue Split Comparison",
      industries: [
        { industry: "Automotive", color: "#e16f3d", fy24: 22.2, fy26e: 26.1 },
        { industry: "IT/ITES", color: "#c45c2a", fy24: 21.9, fy26e: 20.3 },
        { industry: "Industrial / Mfg", color: "#f4a574", fy24: 20.4, fy26e: 14.9 },
        { industry: "Manufacturing", color: "#64748b", fy24: 11.5, fy26e: 9.2 },
        { industry: "Healthcare", color: "#60a5fa", fy24: 0.04, fy26e: 8.2 },
        { industry: "Metals / Steel", color: "#5eead4", fy24: 3.4, fy26e: 5.0 },
        { industry: "Cement", color: "#14b8a6", fy24: 0, fy26e: 3.9 },
      ],
    },
    newBusinessRetention: {
      title: "New Business & Retention: ACV Pipeline & Retention",
      kpiRow1: [
        { primary: "+56%", label: "ACV/Client Growth", sub: "178L to 278L per client FY24-26" },
        { primary: "+42%", label: "RPH Improvement", sub: "35K to 50K per hire FY24-26" },
        { primary: "45%", label: "Churn Reduction", sub: "12.2% down to 6.7%" },
        { primary: "+50%", label: "Productivity Surge", sub: "1.05L to 1.57L per employee" },
      ],
      kpiRow2: [
        { primary: "2,667L", label: "New ACV FY24", sub: "15 clients" },
        { primary: "3,909L", label: "New ACV FY25", sub: "16 clients" },
        { primary: "2,906L", label: "New ACV FY26E", sub: "9 clients" },
      ],
      acvBar: [
        { year: "FY'24", value: 2667 },
        { year: "FY'25", value: 3909 },
        { year: "FY'26", value: 2906 },
      ],
      strengthsTitle: "Sales Engine Strengths",
      strengths: [
        { num: "01", text: "278L Avg ACV/Client FY26E vs. 178L in FY24 (+56%)" },
        { num: "02", text: "6.7% Churn Rate FY26E vs. 12.2% in FY24 (-45%)" },
        { num: "03", text: "93%+ Net Revenue Retention: Strong Customer Stickiness" },
        { num: "04", text: "13 Exclusive Contracts FY26E (260L Value)" },
      ],
    },
    growthJourney: {
      title: "Growth Journey",
      footerNote: "(Founder, CEO, CBO, CFO & CPO slides) – Data to be filled by the finance team.",
      years: ["FY 25", "FY 26", "FY 27", "FY 28", "FY 29", "FY 30"],
      highlightYear: "FY 26",
      revenueYoY: [
        { year: "FY 25", value: 10, label: "$10M" },
        { year: "FY 26", value: 105, label: "105 / $12M" },
        { year: "FY 27", value: 141 },
        { year: "FY 28", value: 187 },
        { year: "FY 29", value: 266 },
        { year: "FY 30", value: 377 },
      ],
      revenueGrowthTag: "~4x Growth",
      ebitdaYoY: [
        { year: "FY 25", bar: 4, marginPct: 4 },
        { year: "FY 26", bar: 8, marginPct: 8 },
        { year: "FY 27", bar: 12, marginPct: 9 },
        { year: "FY 28", bar: 28, marginPct: 15 },
        { year: "FY 29", bar: 64, marginPct: 24 },
        { year: "FY 30", bar: 125, marginPct: 33 },
      ],
      ebitdaGrowthTag: "~30X Growth",
      newAcv: [
        { year: "FY 25", value: 4 },
        { year: "FY 26", value: 4 },
        { year: "FY 27", value: 65 },
        { year: "FY 28", value: 95 },
        { year: "FY 29", value: 125 },
        { year: "FY 30", value: 160 },
      ],
      grossMarginPct: [
        { year: "FY 25", value: 37 },
        { year: "FY 26", value: 41 },
        { year: "FY 27", value: 45 },
        { year: "FY 28", value: 50 },
        { year: "FY 29", value: 54 },
        { year: "FY 30", value: 60 },
      ],
      sidebarKpis: [
        { primary: "6 X", label: "LTV/CAC Ratio In FY26" },
        { primary: ">90%", label: "CSAT consistent over the past 5 years" },
        { primary: "50%", label: "Improvement in People Productivity FY24-26" },
        { primary: "35-40%", label: "Fixed and Advance Revenue" },
      ],
      sidebarBullets: [
        "Sustained profitable growth last 3 years, while self-funding our Tech Journey",
        "4X growth in the next 4 years, powered by Agentic delivery model",
      ],
    },
    revenueBridge: {
      title: "Revenue Bridge FY27 (INR Crores): Target",
      yMax: 160,
      steps: [
        { label: "Revenue FY 2026", value: 105, kind: "total" },
        { label: "Ramp-up FY'26", value: 20, kind: "increase" },
        { label: "Churn", value: -7, kind: "decrease" },
        { label: "Expansion/ Contraction", value: 7, kind: "increase" },
        { label: "New", value: 15, kind: "increase" },
        { label: "OrderBook 2027", value: 140, kind: "final" },
      ],
    },
    unitEconomics: {
      title: "Evolving Unit Economics",
      footerNote: "(Founder, CEO, CBO, CFO & CPO slides) – Data to be filled by the finance team.",
      headers: ["Key Operational Metrics (as % of Revenue)", "FY'25 Previous Year", "FY'26 Previous Year", "FY'27 Current Year", "FY'30 (Target)"],
      rows: [
        { type: "data", metric: "Revenue Growth", fy25: "21%", fy26: "21%", fy27: "21%", fy30: "42%" },
        { type: "section", metric: "Direct Costs" },
        { type: "data", metric: "Job Portal Cost (%)", fy25: "6%", fy26: "6%", fy27: "6%", fy30: "4%" },
        { type: "data", metric: "Direct Salary Cost (%)", fy25: "53%", fy26: "53%", fy27: "53%", fy30: "37%" },
        { type: "summary", metric: "Gross Margins (%)", fy25: "41%", fy26: "41%", fy27: "41%", fy30: "60%" },
        { type: "section", metric: "Indirect Costs" },
        { type: "data", metric: "S&M Cost (%)", fy25: "10%", fy26: "10%", fy27: "10%", fy30: "8%" },
        { type: "data", metric: "G&A Cost (%)", fy25: "16%", fy26: "16%", fy27: "16%", fy30: "12%" },
        { type: "data", metric: "Product Development (%)", fy25: "6%", fy26: "6%", fy27: "6%", fy30: "5%" },
        { type: "data", metric: "PDD", fy25: "1%", fy26: "1%", fy27: "1%", fy30: "1%" },
        { type: "summary", metric: "EBITDA (%)", fy25: "8%", fy26: "8%", fy27: "8%", fy30: "25%" },
      ],
    },
    hiringSourceMix: {
      title: "Hiring Source Mix: FY26",
      donut: [
        { name: "Taggd Sourced", pct: 52, color: "#3884ff" },
        { name: "Others", pct: 22, color: "#9ca3af" },
        { name: "ER (Employee Referral)", pct: 15, color: "#2ecc71" },
        { name: "IJP (Internal Job Posting)", pct: 10, color: "#ec4899" },
        { name: "Campus", pct: 6, color: "#b45309" },
      ],
      seriesColors: {
        "Taggd Sourced": "#3884ff",
        Campus: "#b45309",
        ER: "#2ecc71",
        "IJP / Other": "#ec4899",
      },
      stackedSectors: [
        { sector: "BFSI", series: [
          { name: "Taggd Sourced", pct: 45 },
          { name: "ER", pct: 30 },
          { name: "IJP / Other", pct: 15 },
          { name: "Campus", pct: 10 },
        ] },
        { sector: "Others", series: [
          { name: "Taggd Sourced", pct: 40 },
          { name: "ER", pct: 25 },
          { name: "IJP / Other", pct: 20 },
          { name: "Campus", pct: 15 },
        ] },
        { sector: "Pharma", series: [
          { name: "Taggd Sourced", pct: 50 },
          { name: "ER", pct: 20 },
          { name: "IJP / Other", pct: 20 },
          { name: "Campus", pct: 10 },
        ] },
        { sector: "FMCG", series: [
          { name: "Taggd Sourced", pct: 48 },
          { name: "ER", pct: 22 },
          { name: "IJP / Other", pct: 18 },
          { name: "Campus", pct: 12 },
        ] },
        { sector: "Manufacturing", series: [
          { name: "Taggd Sourced", pct: 42 },
          { name: "ER", pct: 35 },
          { name: "IJP / Other", pct: 15 },
          { name: "Campus", pct: 8 },
        ] },
        { sector: "IT / Tech", series: [
          { name: "Taggd Sourced", pct: 55 },
          { name: "ER", pct: 18 },
          { name: "IJP / Other", pct: 17 },
          { name: "Campus", pct: 10 },
        ] },
        { sector: "Core", series: [
          { name: "Taggd Sourced", pct: 48 },
          { name: "ER", pct: 24 },
          { name: "IJP / Other", pct: 18 },
          { name: "Campus", pct: 10 },
        ] },
        { sector: "Engineering", series: [
          { name: "Taggd Sourced", pct: 44 },
          { name: "ER", pct: 28 },
          { name: "IJP / Other", pct: 18 },
          { name: "Campus", pct: 10 },
        ] },
        { sector: "Automotive", series: [
          { name: "Taggd Sourced", pct: 46 },
          { name: "ER", pct: 26 },
          { name: "IJP / Other", pct: 18 },
          { name: "Campus", pct: 10 },
        ] },
      ],
      insights: [
        "Engineering and Automotive show strong internal mobility",
        "Manufacturing and BFSI – have the highest ER contribution",
        "JAS – has the highest contribution of campus recruiters",
      ],
      footerNote: "",
    },
    peopleCapability: {
      title: "People Capability",
      subtitle: "Stable execution bench + continuous capability building",
      bannerMetrics: [
        { value: "666+", label: "Workforce" },
        { value: "70%", label: "People managers promoted internally" },
        { value: "5+ Years", label: "Average Tenure – Manager's & above" },
        { value: "67%", label: "Gender diversity including women & LGBTQ+" },
        { value: "30%", label: "Attrition" },
      ],
      deliveryTitle: "Delivery Capability and Enablement",
      deliveryBadge: "80%+ Training Coverage",
      deliveryItems: [
        {
          title: "Domain Expertise",
          body: "Specialised training in high-demand and priority verticals such as Automotive, IT, Pharmaceuticals.",
          icon: "building",
        },
        {
          title: "Recruitment Excellence",
          body: "For business-as-usual operational excellence.",
          icon: "star",
        },
        {
          title: "Behavioural Skills",
          body: "Training in advanced candidate communication, stakeholder management & negotiation strategies.",
          icon: "message",
        },
        {
          title: "TARA Enablement",
          body: "Workflow adoption, optimisation and quality calibration.",
          icon: "rocket",
        },
      ],
      leadershipTitle: "Leadership Pipeline",
      leadershipItems: [
        { title: "Emerging Leaders (3 cohorts)", body: "Building next generation of management.", icon: "crown" },
        { title: "Women Leaders (1 program)", body: "Dedicated development track for senior women leaders.", icon: "user" },
      ],
      distributionTitle: "Workforce Distribution",
      wlDistribution: [
        { level: "WL1", pct: 75, color: "#9ca3af" },
        { level: "WL2", pct: 21, color: "#e16f3d" },
        { level: "WL3", pct: 3, color: "#fbcfe8" },
        { level: "WL4", pct: 2, color: "#7f1d1d" },
        { level: "WL5", pct: 0, color: "#111827" },
      ],
      footerLine: "Training coverage is maintained on an ongoing basis",
    },
    costTeamStructure: {
      title: "Cost Team Structure",
      summaryCards: [
        { primary: "10 to 30%", sub: "Incentive variable depending upon role & function" },
        { primary: "579", sub: "Customer Success 87% of team in delivery" },
        { primary: "12", sub: "Tech team members Building TARA platform" },
        { primary: "7.6 Yrs", sub: "Avg Senior Tenure, Deep institutional knowledge" },
      ],
      headcountBySbu: {
        columns: ["SBU", "Function", "East Region", "North Region", "South Region", "West Region", "Grand Total"],
        rows: [
          { sbu: "BG", function: "Demand Generation", east: "7", north: "0", south: "0", west: "0", total: "7" },
          { sbu: "BG", function: "Marketing", east: "0", north: "8", south: "4", west: "2", total: "14" },
          { sbu: "BG", function: "Sales", east: "0", north: "2", south: "1", west: "1", total: "4" },
          { sbu: "BG", function: "Solutioning", east: "0", north: "1", south: "1", west: "0", total: "2" },
          { sbu: "Corporate", function: "Corporate", east: "1", north: "2", south: "1", west: "1", total: "5" },
          { sbu: "Corporate", function: "Finance", east: "0", north: "4", south: "3", west: "2", total: "9" },
          { sbu: "ISG", function: "IT Support", east: "0", north: "1", south: "1", west: "1", total: "3" },
          { sbu: "ISG", function: "Lifeline", east: "0", north: "1", south: "1", west: "0", total: "2" },
          { sbu: "ISG", function: "People & Culture", east: "3", north: "8", south: "6", west: "4", total: "21" },
          { sbu: "ISG", function: "Business Excellence", east: "0", north: "3", south: "3", west: "2", total: "8" },
          { sbu: "Technology", function: "Technology", east: "1", north: "4", south: "4", west: "3", total: "12" },
          { sbu: "RPO", function: "Customer Success", east: "0", north: "235", south: "180", west: "164", total: "579" },
        ],
        grandTotal: { east: "11", north: "259", south: "205", west: "191", all: "666" },
      },
      tenureByBand: [
        { band: "WL1", headcount: "495", avgTenure: "1.98" },
        { band: "WL2", headcount: "139", avgTenure: "3.72" },
        { band: "WL3", headcount: "20", avgTenure: "3.47" },
        { band: "WL4", headcount: "10", avgTenure: "8.97" },
        { band: "WL5", headcount: "2", avgTenure: "19.79" },
      ],
      incentiveGrid: [
        { band: "WL1", sales: "30%", recruitmentOps: "10%", isg: "10%", technology: "10%" },
        { band: "WL2", sales: "30%", recruitmentOps: "15%", isg: "12%", technology: "12%" },
        { band: "WL3", sales: "30%", recruitmentOps: "18%", isg: "15%", technology: "15%" },
        { band: "WL4", sales: "30%", recruitmentOps: "22%", isg: "18%", technology: "18%" },
        { band: "WL5", sales: "30%", recruitmentOps: "25%", isg: "22%", technology: "22%" },
      ],
      footerNote: "(Founder, CEO, CBO, CFO & CPO slides)",
    },
  };
}
